# Generated by Django 2.2.19 on 2022-08-18 20:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Название ингредиента')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Количество ингредиента')),
                ('measurement_unit', models.CharField(choices=[('банка', 'банка'), ('батон', 'батон'), ('бутылка', 'бутылка'), ('веточка', 'веточка'), ('г', 'г'), ('горсть', 'горсть'), ('долька', 'долька'), ('звездочка', 'звездочка'), ('зубчик', 'зубчик'), ('капля', 'капля'), ('кг', 'кг'), ('кусок', 'кусок'), ('л', 'л'), ('лист', 'лист'), ('мл', 'мл'), ('пакет', 'пакет'), ('пакетик', 'пакетик'), ('пачка', 'пачка'), ('пласт', 'пласт'), ('по вкусу', 'по вкусу'), ('пучок', 'пучок'), ('ст. л.', 'ст. л.'), ('стакан', 'стакан'), ('стебель', 'стебель'), ('стручок', 'стручок'), ('тушка', 'тушка'), ('упаковка', 'упаковка'), ('ч. л.', 'ч. л.'), ('шт.', 'шт.'), ('щепотка', 'щепотка')], max_length=15, verbose_name='Величина измерения ингредиента')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=15, unique=True, verbose_name='Теги')),
                ('color', models.CharField(max_length=7, verbose_name='Цветовой HEX-код')),
                ('slug', models.SlugField(max_length=15, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название рецепта')),
                ('image', models.ImageField(upload_to='recipes/', verbose_name='Картинка')),
                ('text', models.TextField(verbose_name='Описание рецепта')),
                ('cooking_time', models.PositiveIntegerField(help_text='Время приготовления в минутах', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10080)], verbose_name='Время приготовления в минутах')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='Автор рецепта')),
                ('ingredients', models.ManyToManyField(related_name='recipes', to='recipes.Ingredients', verbose_name='Ингредиенты')),
                ('tags', models.ManyToManyField(related_name='recipes', to='recipes.Tags', verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
    ]
