# Generated by Django 2.2.19 on 2022-08-24 20:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_ingredients_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='quantity',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Количество ингредиента'),
            preserve_default=False,
        ),
    ]
