# Generated by Django 2.2.19 on 2022-09-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20220901_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=1, upload_to='recipes/', verbose_name='Картинка'),
            preserve_default=False,
        ),
    ]
