# Generated by Django 2.2.19 on 2022-09-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_remove_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=1, upload_to='recipes/image/', verbose_name='Картинка'),
            preserve_default=False,
        ),
    ]
