# Generated by Django 2.2.19 on 2022-09-01 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220830_1857'),
        ('users', '0002_auto_20220901_0141'),
    ]

    operations = [
    ]
