# Generated by Django 2.2.19 on 2022-09-01 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_20220901_1006'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
